name: condinilm
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h2bfc596_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py312hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alembic==1.17.2
      - altair==6.0.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.4.0
      - blinker==1.9.0
      - bottle==0.13.4
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - einops==0.8.1
      - einx==0.3.0
      - filelock==3.20.1
      - fonttools==4.61.1
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - mako==1.3.10
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.0
      - narwhals==2.14.0
      - networkx==3.6.1
      - numpy==2.4.0
      - omegaconf==2.3.0
      - optuna==4.6.0
      - optuna-dashboard==0.20.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - six==1.17.0
      - smmap==5.0.2
      - sqlalchemy==2.0.45
      - streamlit==1.52.2
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tornado==6.5.4
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - werkzeug==3.1.4
      - yarl==1.22.0
prefix: /Users/yu/miniconda3/envs/condinilm
