REFIT:
  Dishwasher:
    app:  Dishwasher
    house_with_app_i: [1, 2, 3, 5, 6, 7, 9, 10, 13, 15, 16, 18, 20]
  WashingMachine:
    app:   WashingMachine
    house_with_app_i: [1, 2, 3, 5, 6, 7, 8, 9, 10, 13, 15, 16, 17, 18, 19]
  Kettle:
    app:  Kettle
    house_with_app_i: [2, 3, 4, 5, 6, 7, 9, 12, 13, 15, 19, 20]
  Microwave:
    app:  Microwave
    house_with_app_i: [2, 3, 4, 6, 8, 9, 10, 12, 13, 15, 17, 18, 19, 20]

UKDALE:
  WashingMachine:
    app:  washing_machine
    ind_house_train_val: [1, 3, 4, 5]
    ind_house_test: [2]
    overlap: 0.5
  Dishwasher:
    app:  dishwasher
    ind_house_train_val: [1, 3, 4, 5]
    ind_house_test: [2]
    overlap: 0.5
  Kettle:
    app:  kettle
    ind_house_train_val: [1, 3, 4, 5]
    ind_house_test: [2]
    overlap: 0.5
  Microwave:
    app:  microwave
    ind_house_train_val: [1, 3, 4, 5]
    ind_house_test: [2]
    overlap: 0.5
  Fridge:
    app:  fridge
    ind_house_train_val: [1, 3, 4, 5]
    ind_house_test: [2]
    overlap: 0.5
